- src/polyswarmclient/ambassador.py
This is a workaround, should be properly fixed by #5
> Fix ambassador race

- src/polyswarmclient/arbiter.py
> Add chain arg when getting bounties.

- src/polyswarmclient/arbiter.py
- src/polyswarmclient/bountiesclient.py
Return None if get_assertion or get_bounty fail
> Check success flag, return None if false.

- docker/windows/pscwin/install-ps-cli.ps1
Tested locally.  The new command works better with windows. updates pip without access denied errors with local testing
> powershell script edit

- .gitlab-ci.yml
- HISTORY.md
- README.md
- setup.py
only thing left to do is to add a check to ensure that the git tag == setup.py version string.
> preparing for PyPI publishing.

- src/arbiter/clamav.py
adds clamav arbiter related to https://github.com/polyswarm/development-private/issues/115
> add clamav arbiter

- src/ambassador/__main__.py
- src/arbiter/__main__.py
- src/microengine/__main__.py
I added an exception at the beginning of `choose_backend` to make the error explicit, rather than relying on the existing exceptions later in the function.
> Remove default backend of 'scratch'.

- docker/windows/choco/requirements.txt
- requirements.txt
Moved ethash to top level of repo
> updated to use PS's custom repo for ethash

- docker/windows/choco/build-ps-client.ps1
- requirements.txt
> creating PS's ethash with powershell.

- src/microengine/producer.py
adds a timestamp to the redis message to determine the time placed on the queue
> add ts to redis message

- src/microengine/producer.py
> fix datetime string

- docker/ci-image/Dockerfile
> fix dockerfile

- .gitlab-ci.yml
- docker/Dockerfile
- docker/windows/Dockerfile
- requirements.txt
Refactoring CI to have stages as:
Build -> Test -> Release -> Deploy
And jobs inside each stage run in parallel. This is built on top of the https://12factor.net/ philosophy.
- Master branch triggers releases for latest docker images
- Tags trigger releases for tagged docker images and pypi releases
- Build and Test stages run on every push
- Deploy runs on master branch
- Filter pypi releases based on tags in the format X.X.X, do execute for other tags
> Refactoring ci

- .gitlab-ci.yml
Removing double quotes from linux commands that were breaking CI.
> fixing problem with missing double quotes

- .gitlab-ci.yml
Fixing problem with missing aws authentication when running outside of aws.
> run deployment stage in kubernetes

- .gitlab-ci.yml
Working e2e tests. Pulls the image from the build stage and run against eicar engine sending a malicious and a non-malicious file. Wait for the bounty to finish.
> adding e2e tests

- .gitlab-ci.yml
Adding a manual trigger in a special tag for multi-projects integration test.
> adding a manual tagging feature for exceptional pipeline runs

- .gitlab-ci.yml
Windows does not like ternary operators.
> fix windows release image tag syntax

- requirements.txt
- setup.py
pin the version of polyswarm-artifact, else our image could have older versions in it.
> pin version of polyswarm-artifact, so it actually gets the newer one.

- docker/artifacts/benign/benign
- src/ambassador/eicar.py
- src/arbiter/eicar.py
Adding a simple eicar arbiter that is used in `e2e`.
> Adding eicar sample arbiter

- src/microengine/eicar.py
Making the test microengine find eicar anywhere and respond to urls.
> making the test microengine more generic
