polyswarm/polyswarm-client

- src/polyswarmclient/__init__.py
- src/polyswarmclient/ambassador.py
- src/polyswarmclient/arbiter.py
- src/polyswarmclient/microengine.py
- src/polyswarmclient/reporter.py
Related to polyswarm/ambassador#1 (thanks @strazzere!) , currently we've decided its better to exit on error while we come up with a better recovery strategy given potentially stale state in the client.
> Handle connection interruptions by exiting with failure

- docker/Dockerfile
- setup.py
- src/ambassador/filesystem.py
- src/arbiter/verbatim.py
- src/arbiter/verbatimdb/__main__.py
- src/arbiter/verbatimdb/db.py
- src/corpus/__init__.py
- src/corpus/test_dl.py
Replace `withartifacts` docker tag with a Pythonic puller that downloads a basic corpus to arbiter and ambassador. Tested in staging.
> Vartifacts

- docker/windows/pscwin/choco.ps1
This forces powershell to use TLS 1.2.  Hope this fixes e2e issue downloading the choco install
> force PS to TLS 1.2

- README.md
- setup.py
- src/ambassador/__main__.py
- src/ambassador/eicar.py
- src/ambassador/filesystem.py
- src/arbiter/__main__.py
- src/arbiter/verbatim.py
- src/microengine/__main__.py
- src/microengine/clamav.py
- src/microengine/eicar.py
- src/microengine/multi.py
- src/microengine/scratch.py
- src/microengine/yara.py
- src/polyswarmclient/abstractambassador.py
- src/polyswarmclient/abstractarbiter.py
- src/polyswarmclient/abstractmicroengine.py
- src/polyswarmclient/abstractscanner.py
* Renamed `polyswarmclient.microengine.Microengine` to `polyswarmclient.abstractractmicroengine.AbstractMicroengine`. 
* Now throw an exception if AbstractMicroengine.scan() is called and a scanner was not provided to the subclass's super() constructor.
* Updated sample microengines to use AbstractMicroengine instead of Microengine. 
* Bumped python module version number to 0.2.0 since this is a breaking change. 
* Updated README.md to include a notice that this is a breaking change.
> Renamed Microengine AbstractMicroengine and associated updates

- HISTORY.md
- setup.py
* updated version to 1.0rc5. 
* filled out major changes for each release in the HISTORY.md file.
We should add any remaining changes to the HISTORY.md before we cut rc5.
> bump ver to 1.0rc5

- src/balancemanager/__init__.py
* fixed another case of asyncio.Lock() being used before the loop is changed. changed it to create the locks after the client is run using run_on.register().
> fixed use of asyncio.Lock() in balancemanger.Maintainer()

- src/polyswarmclient/__init__.py
This code calls `os._exit` which is a hard exit. No exception handlers/destructors/exit routines are run, threads die, etc.
This begs the question:
Can we handle clean-up manually *prior* to calling `sys.exit`?
Can we manually see what exception handler *would* be called if an exception *were* to be invoked (possibly allowing us to fix it)? If it's not an exception handler issue - is it outstanding threads?
[_voice grows increasingly insane_] Can we reach into a python coredump and reconcile regular python pdb symbols with interpreter state to reconstruct where in the application it is hanging at a "high level"?
The possibilities for how to handle this are endless but this code here does have the advantage of working now and showing no clear defects.
> Exit Client with `os.exit()' when sys.platform == 'win32'

- src/polyswarmclient/transaction.py
Fixes following error
```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
result = coro.send(None)
File "/usr/local/lib/python3.5/site-packages/polyswarmclient/events.py", line 359, in run
return await super().run(bounty_guid, chain)
File "/usr/local/lib/python3.5/site-packages/polyswarmclient/events.py", line 49, in run
local_ret = await cb(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/polyswarmclient/abstractambassador.py", line 246, in __handle_settle_bounty
ret = await self.client.bounties.settle_bounty(bounty_guid, chain)
File "/usr/local/lib/python3.5/site-packages/polyswarmclient/bountiesclient.py", line 411, in settle_bounty
success, result = await transaction.send(chain, api_key=api_key)
File …
```
> Fix missing parens for function call

- docker/ci-image/Dockerfile
packer failing CI.  Checking if new packer update it the issue.  rolling back to v1.3.1
> downgrade packer to a known working version pre CI changes

- src/polyswarmclient/config.py
Fix regression that caused all loggers to be tied to polyswarmclient log level.
> Restore ability to separate polyswarmclient from other loggers

- docker/windows/base/polyswarm-profile.ps1
- tests/conftest.py
This fixes a fatal file permission issue on the temporary files created when running under Windows.
> Fix `NamedTemporaryFile' permissions issue in MockClient under Windows

- docker/windows/base/polyswarm-profile.ps1
- requirements.txt
- src/polyswarmclient/utils.py
- src/polyswarmclient/verifiers.py
- tests/conftest.py
- tests/test_client.py
- tests/test_verifiers.py
This patch removes all instances of the `ethereum` module referenced in `polyswarm-client`'s Python code, ending a slew of Windows build issues arising from this package's dependencies.
Today, the amount of code referencing the `ethereum` module in `polyswarm-client` has shrunk to the extent that only it's implementation of sha3/Keccak remains; All usages of this `sha3` function have been replaced with the reference implementation upstream along with unit tests to verify absence of regressions in functions calling `ethereum.utils.sha3`
> Remove ethereum module

- .gitlab-ci.yml
- HISTORY.md
- setup.py
* removed e2e testing
* removed old windows python package builds (wheels)
* bump version to 1.4.2. 
* build new windows image after push to pypi, so it can use the new polyswarm-client version.
> clean up windows, bump version to 1.4.2

- docker/windows/base/Dockerfile
Do not merge until we have tested all of the microengines on psc 1.4.2
> Remove custom `pyethash'

- kick_downstream.py
Needs review from @mrtizmoatwork  - What do you think about breaking `kick_downstream.py` out so it can be shared between PSC && PSCWIN?
> kick_downstream should use master branch for all downstream repos

- src/worker/__init__.py
We see a number of `socker.gaierror` in workers, which builds up to 15 seconds, then stays there forever causing missed bounties. 
This reset that value on a successful scan result sent back over redis.
> Reset tries value on successful response

- .gitlab-ci.yml
Fixing problem when interpolating strings in windows.
> using doble quotes in order to interpolate the environment variable

- tests/test_client.py
Increasing tests timeout from 5 to 15 seconds.
> increasing test timeouts to 15 seconds

- src/polyswarmclient/producer.py
This is the result of us seeing some weird behavior in prod, and I believe is the fix.
The behavior in question was as follows: engines would begin reporting every bounty they got off their queue as expired. Times on producer/workers appeared to be synced properly. The queues themselves appeared to be empty 99% of the time, but the bounties they were reporting grabbing were very old (minutes to hours old).
After some looking around for root cause, I believe what is happening is that these `blpop`s waiting on results are blocking all the redis connections (10 max in the pool by default), meaning that the producers will only allow ~10 outstanding bounties at any given time (as it will start waiting on results for all of them). Any bounties scheduled after this begin to pile up in the async …
> Don't block redis conn with blpop

- src/polyswarmclient/abstractscanner.py
It looks like metadata is intended to be parsable as a json string and this should be reflected in the comments.
> Indicate metadata should be json-parsable string

- src/polyswarmclient/abstractmicroengine.py
When running microengines that are not in the producer/consumer model, the original `fetch_and_scan()` code discards the `ScanResult()` instance from the scanner, returning an empty `ScanResult()` instead, which means "no assertion". This fix uses the existing `ScanResult()` in case the bit mask is set.
This bug was compromising our `e2e` tests. Thanks @mrtizmoatwork for the help looking into it.
> Do not discard results when running solo microengines

- src/worker/__init__.py
we shouldn't be crashing with an unhandled exception if we can't gracefully shut down
> change exception to warning

- .gitlab-ci.yml
This is an attempt to fix a bad env var inheritance when triggering a downstream pipeline. This can only be tested in the master branch unfortunately.
> trying to fix bad env var inheritance

- requirements.txt
- setup.py
`async-timeout<4.0,>=3.0` is required by `aiohttp` whereas `aioredis` doesn't request a particular version.
We could install `aiohttp` before `aioredis` as well, but let's make it explicit for future generations.
> Sync requirements.txt & setup.py, downgrade async-timeout.

- .gitignore
- README.md
- docker/Dockerfile
- docker/windows/Dockerfile
This is needed to work with newer python packaging formats, which we are using in microengine-utils project.
> Update pip version in our docker images

- .gitlab-ci.yml
We've moved this logic into `polyswarm-client-internal`
> Don't build engine images in CI
